### ISSUE TITLE
The pagination component is not responsive (if the width is less than 555px)

### ISSUE THREAD

**Issue by avid21** [quantstamp/quantstamp_web_support#2]
## Expected Behavior
The pagination component on `https://quantstamp.com/public-reports?page=8` should be responsive and not break.

## Actual Behavior
The pagination component breaks if the width of the screen is less than 555px.

## Steps to Reproduce the Problem

1. Go to this page; https://quantstamp.com/public-reports?page=8
2. Resize the width of the screen to less than 555px. 

## Details

  **- URL:** 
https://quantstamp.com/public-reports?page=8

  **- Screenshots:**
![image](https://user-images.githubusercontent.com/25740248/38565114-6baa014c-3d1b-11e8-9224-7ef329f23387.png)

##  Additional Information  
  **- Contact Information (Optional):**  

> Email: innovation.noel@gmail.com

> Telegram: @noelyoo

  **- Operating System:** 
> OSX 10.13.4

  **- Browser:** 
> Chrome

  **- Device:** 
> MacBook Pro

**Comment by avid21** [comment]
Resolved

**Comment by MeiMcCullar** [comment]
Noted! Thank you!
