### ISSUE TITLE
the "Why should I create an account" link just reloads signup page

### ISSUE THREAD

**Issue by avid21** [quantstamp/quantstamp_web_support#5]
## Expected Behavior
When you click the "Why should I create an account" link on https://quantstamp.com/signup, it should give you an explanation about why you should sign up.

<a href="/signup">Why should I create an account?</a>
https://quantstamp.com/signup

## Actual Behavior
When you click the "Why should I create an account" link on https://quantstamp.com/signup, it just reloads the signup page. 

## Steps to Reproduce the Problem

1. go to https://quantstamp.com/signup
2. click the "Why should I create an account" link 

## Details

  **- URL:** 

> https://quantstamp.com/signup

  **- Screenshots:**
  
![image](https://user-images.githubusercontent.com/25740248/39221353-6b6f3a6a-4871-11e8-9ed9-0dd3d8c5910c.png)

##  Additional Information  
  **- Contact Information (Optional):**  
> Email: innovation.noel@gmail.com

> Telegram: @noel_yoo

  **- Operating System:** 
> Mac OSX

  **- Browser:** 
> Chrome

  **- Device:** 
> Macbook Pro

**Comment by MeiMcCullar** [comment]
Noted! Thank you!

@Matt-Holland

**Comment by avid21** [comment]
Fixed
