### ISSUE TITLE
Clicking 'Sign Up' button without valid inputs should not change pathname to '/users'  

### ISSUE THREAD

**Issue by avid21** [quantstamp/quantstamp_web_support#7]
## Expected Behavior
When you click 'Sign Up' button without valid inputs, the pathname '/signup' should stay the same.
## Actual Behavior
When you click 'Sign Up' button without valid inputs, the pathname changes from '/signup' to '/users'.

## Steps to Reproduce the Problem

1. go to https://quantstamp.com/signup 
2. leave all the input fields empty
3. click 'Sign Up' button
4. check pathname

## Details

  **- URL:** 

> https://quantstamp.com/signup

  **- Screenshots:**
  
![image](https://user-images.githubusercontent.com/25740248/39412999-2f605d28-4c5f-11e8-8d17-1379221aee19.png)

  **- Other:**

##  Additional Information  
  **- Contact Information (Optional):**  

> Email: innovation.noel@gmail.com
> Telegram: @noel_yoo

  **- Operating System:** 
> Example: macOS 10.13.4 (17E199)

  **- Browser:** 
> Example: Chrome

  **- Device:** 
> Example: Macbook Pro

**Comment by MeiMcCullar** [comment]
This is a devise gem routing behavior. Not critical. 
@Matt-Holland
